#TUPLAS
#LAS TUPLAS SON IMUTABLES Y UNA VEZ CREADAS NO PERMITEN MODIFICACIONES

#NO SE PERMITE:
#    ANIADIR, ELIMINAR, MOVER ELEMENTOS
#    EXTRAER PORCIONES
#    BUSQUEDAS

#SI PERMITE:
#    COMPROBAR SI UN ELEMENTO SE ENCUENTRA

#VENTAJAS:
#    SE EJECUTAN MAS RAPIDO
#    OCUPA MENOS ESPACIO EN MEMORIA
#    FORMATEAN STRINGS
#    PUEDEN UTILIZARSE COMO CLAVES DE UN DICCIONARIO

#CREACION DE TUPLA
mitupla=("Juan", 13,1,1995,13)

#CONVERTIR TUPLA A LISTA
milista=list(mitupla)

#CONVERTIR LISTA A TUPLA
convertirLista=tuple(milista)

print("Juan" in convertirLista)

#CUANTAS VECES SE ENCUENTRA UN ELEMENTO EN LA TUPLA
print(convertirLista.count(13))

#LONGITUD DE UNA TUPLA DE ACUERDO A SUS INDICES
print(len(convertirLista))

#TUPLA UNITARIA MANERA CORRECTA DE DECLARARLO
tuplaunitaria=("Juan",)
print(len(tuplaunitaria))

#CREACION DE TUPLA, SE PUEDE HACER SIN PARENTESIS
#NO SE RECOMIENDA USARLO, YA QUE PUEDE CAUSAR CONFUSION
#REALIZA EL EMPAQUETADO DE LA TUPLA
tuplasinp = "Juan", 1, 2 
print(tuplasinp)

#DESEMPAQUETADO DE TUPLA
#ASIGNA LOS VALORES DE LA TUPLA A LAS VARIABLES
tupla=("Juan", 13, 1, 1995)
nombre, dia, mes, agno = tupla
print(nombre)
print(dia)
print(mes)
print(agno)